[package]
name = "scroll_derive"
version = "0.1.0"
authors = ["m4b <m4b.github.io@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
syn = "0.10.5"
quote = "0.3.10"

[dev-dependencies.scroll]
version = "0.2.0"
path = "../scroll"
